In [24]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [2]:
veri = pd.read_csv('Advertising.csv')
veri2 = veri.drop(veri.columns[0],axis=1)
veri2

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [3]:
y = pd.DataFrame(veri2['sales'])
y

sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [4]:
X = pd.DataFrame(veri2[['TV','radio','newspaper']])
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [5]:
lm = sm.OLS(y,X)
model = lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Thu, 07 Mar 2024   Prob (F-statistic):                   2.43e-171
Time:                        21:17:50   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
lm = LinearRegression()
model = lm.fit(X,y)


In [7]:
model.intercept_

array([2.93888937])

In [8]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [9]:
yeni_veri = [[30],[10],[40]]
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [10]:
model.predict(yeni_veri)

c:\Users\omerf\anaconda3\envs\tensoeflow2\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [11]:
y[0:10]

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9
5    7.2
6   11.8
7   13.2
8    4.8
9   10.6

In [12]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [13]:
from sklearn.metrics import mean_squared_error
# hata karel ortalaması
MSE =mean_squared_error(y,model.predict(X))
MSE

2.784126314510936

In [14]:
# hata karaler ortalaması karekökü

RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=99)

In [17]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [18]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [19]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [20]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [21]:
liner_reg = LinearRegression()
coklu_model = liner_reg.fit(X_train,y_train)

In [22]:
# eğitim hatası
np.sqrt(mean_squared_error(y_train,coklu_model.predict(X_train)))

1.7236824822650754

In [23]:
# test hatası 
np.sqrt(mean_squared_error(y_test,coklu_model.predict(X_test)))

1.431278313830164

In [25]:
# k-katlı cv

cross_val_score(coklu_model,X_train,y_train,cv=10,scoring='neg_mean_squared_error')

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [26]:
# cv mse 
np.mean(-cross_val_score(coklu_model,X_train,y_train,cv=10,scoring='neg_mean_squared_error'))

3.317028974234124

In [28]:
# cv rmse(karekök)
np.sqrt(np.mean(-cross_val_score(coklu_model,X_train,y_train,cv=10,scoring='neg_mean_squared_error')))

1.821271252239524